### ISSUE TITLE
API documentation specifies 8 recent and top games, but seems to only deliver 4

### ISSUE THREAD

**Issue by maxim-devereaux** [lichess-org/lila-openingexplorer#160]
E.g. as used for Lichess: https://explorer.lichess.ovh/lichess?variant=standard&speeds=blitz,rapid,classical&ratings=2200,2500&fen=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201&topGames=8&recentGames=0

Specifying <=4 for topGames or recentGames works as expected, but values >4 only give 4 results.

Perhaps caused by the limits / truncation imposed in:
https://github.com/lichess-org/lila-openingexplorer/blob/master/src/model/lichess.rs
(lines 18, 19, 424)?

**Comment by niklasf** [comment]
Thanks. The documentation wasn't accurate.

Note that with the way the games are stored, the truncation is required for correctness. So the only way to get more games would be to raise the limit in the constant and reindex, which would make the database larger. That's why the much smaller masters database and individual player databases have higher limits.
